import {
  Button,
  Flex,
  Grid,
  GridItem,
  Heading,
  Input,
  Table,
  TableContainer,
  Tbody,
  Td,
  Text,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid as="main" gap="4" templateColumns="repeat(5, 1fr)">
        <GridItem colSpan={5}>
          <Heading as="h1" size="lg" noOfLines={1}>
            Product List Page
          </Heading>
        </GridItem>

        <GridItem colStart={5}>
          <Input
            placeholder="Search Product"
            maxW="500px"
            border="2px"
            borderColor="gray.300"
            shadow="sm"
          />
        </GridItem>

        <GridItem colSpan={5}>
          <TableContainer
            border="2px"
            borderColor="gray.300"
            rounded="sm"
            shadow="sm"
          >
            <Table variant="striped">
              <Thead borderBottom="2px" borderColor="gray.300">
                <Tr>
                  <Th>Product Name</Th>
                  <Th>Brand</Th>
                  <Th>Price</Th>
                  <Th>Stock</Th>
                  <Th>Category</Th>
                </Tr>
              </Thead>
              <Tbody>
                <Tr>
                  <Td>inches</Td>
                  <Td>millimetres (mm)</Td>
                  <Td>25.4</Td>
                  <Td>25.4</Td>
                  <Td>25.4</Td>
                </Tr>
                <Tr>
                  <Td>feet</Td>
                  <Td>centimetres (cm)</Td>
                  <Td>25.4</Td>
                  <Td>25.4</Td>
                  <Td>25.4</Td>
                </Tr>
                <Tr>
                  <Td>yards</Td>
                  <Td>metres (m)</Td>
                  <Td>25.4</Td>
                  <Td>25.4</Td>
                  <Td>25.4</Td>
                </Tr>
              </Tbody>
            </Table>
          </TableContainer>
        </GridItem>

        <GridItem colStart={5}>
          <Flex gap={2}>
            <Button colorScheme="gray" shadow="sm">
              Prev
            </Button>

            <Text sx={{ margin: "auto 0" }} w="20">
              1 / 2 page
            </Text>

            <Button colorScheme="gray" shadow="sm">
              Next
            </Button>
          </Flex>
        </GridItem>
      </Grid>
    </div>
  );
}
